#%RAML 1.0 DataType
type: object
properties:
  Name:
    type: string
    required: false
  isTest:
    type: boolean
    required: false
  Account_Classification:
    type: string
    required: false
  Industry:
    type: string
    required: false
  Subvertical:
    type: string
    required: false
  SBQQ__TaxExempt:
    type: string
    required: false
  CurrencyIsoCode:
    type: string
    required: false
  OwnerID:
    type: string
    required: false
  RecordTypeId:
    type: string
    required: false
  Description:
    type: string
    required: false
  BillingStreet:
    type: string
    required: false
  BillingCity:
    type: string
    required: false
  BillingPostalCode:
    type: string
    required: false
  BillingStateCode:
    type: string
    required: false
  BillingCountryCode:
    type: string
    required: false
  QS_Bill_To_Email:
    type: string
    required: false
  Phone:
    type: string
    required: false
  APIMBOGUID:
    type: string
    required: false
  AccountSource:
    type: string
    required: false